# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a95d0a060451384ece79915220856f0b7304597543c5b167c0085d41b694e4c039ef1687673387f708ced39ed47cce51f35301299669554521606234cbe5d21

test:
  secret_key_base: 852a4b74cd6eb38ece379c7c52bc03a4f0bcda398e208ff7481eea404275cdeb99d89de9d1447661fa93f1ba686e122d98f60b770c3d582b5f286d4ed1a82c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
